# Generated by Django 3.0.5 on 2020-05-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
