# Generated by Django 3.0.5 on 2020-05-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='closed_date',
            field=models.DateField(null=True),
        ),
    ]
