# Generated by Django 3.0.5 on 2020-05-04 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('case', '0002_auto_20200503_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_date', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_case', to='case.Case')),
                ('lab_attendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_lab_attendant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
